### ISSUE TITLE
Workflow: How to insert fixtures

### ISSUE THREAD

**Issue by tomitrescak** [Sanjo/meteor-jasmine#121]
Sanjo, I know you have responded this question in several threads, but this information is now scattered in between them with no complete answer available. You created a really cool solution with that GIST, but it's not clear where the file belongs. Would you find time to put together a small guide and update the example application?

Thanks!

**Comment by Sanjo** [comment]
Yes I will do this. Thanks for the request.

**Comment by Sanjo** [comment]
I've added a new page to the wiki: https://github.com/Sanjo/meteor-jasmine/wiki/Database-Fixtures-for-Integration-Tests.

If you have some improvement suggestions, let me know.

**Comment by geekyme** [comment]
@Sanjo When I included that script, my tests just stop running altogether. 

![image](https://cloud.githubusercontent.com/assets/977460/6270469/37e3f1aa-b895-11e4-8f86-2ed9263a7e10.png)

**Comment by Sanjo** [comment]
@geekyme Look for an error. If there is none in the console, look in the log files in the directory .meteor/local/log/

**Comment by geekyme** [comment]
@Sanjo 

```
[velocity-mirror] Mirror is initializing...
Resetting database

/Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;      
              ^
TypeError: Object #<Object> has no method 'reject'
  at /Users/shawnlim/Documents/Code/meteorjs/storyline-2.0/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:39:28
  at /Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:524:5
  at /Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:445:7
  at /Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:163:16
  at commandHandler (/Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:706:16)
  at /Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1843:9
  at Server.Base._callHandler (/Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
  at /Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
  at [object Object].MongoReply.parseBody (/Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
  at [object Object].<anonymous> (/Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
  at [object Object].emit (events.js:95:17)
  at [object Object].<anonymous> (/Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
  at [object Object].emit (events.js:98:17)
  at Socket.<anonymous> (/Users/shawnlim/.meteor/packages/mongo/.1.0.11.vvoea5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:422:22)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:764:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)

```

that corresponds to the _.reject piece of code 

```
resetDatabase = function () {
  console.log('Resetting database');
 
  // safety check
  if (!process.env.IS_MIRROR) {
    console.error('velocityReset is not allowed outside of a mirror. Something has gone wrong.');
    return false;
  }
 
  var fut = new Future();
 
  var collectionsRemoved = 0;
  var db = Meteor.users.find()._mongo.db;
  db.collections(function (err, collections) {
 
    var appCollections = _.reject(collections, function (col) {
      return col.collectionName.indexOf('velocity') === 0 ||
        col.collectionName === 'system.indexes';
    });
 
    _.each(appCollections, function (appCollection) {
      appCollection.remove(function (e) {
        if (e) {
          console.error('Failed removing collection', e);
          fut.return('fail: ' + e);
        }
        collectionsRemoved++;
        console.log('Removed collection');
        if (appCollections.length === collectionsRemoved) {
          console.log('Finished resetting database');
          fut['return']('success');
        }
      });
    });
 
  });
 
  return fut.wait();
};

```

_ got stubbed maybe?
