### ISSUE TITLE
Error with build in --debug mode

### ISSUE THREAD

**Issue by think01** [Sanjo/meteor-jasmine#160]
I generated the Meteor bundle with `meteor build --debug`. When I deploy and start the application in my test machine I get this:

```
/var/nodejs/minerva/programs/server/node_modules/fibers/future.js:173
                                                throw(ex);
                                                      ^
TypeError: Object #<Object> has no method 'registerTestingFramework'
  at [object Object]._.extend.registerWithVelocity (/var/nodejs/minerva/programs/server/packages/sanjo_jasmine.js:197:14)
  at Package (/var/nodejs/minerva/programs/server/packages/sanjo_jasmine.js:2009:36)
  at /var/nodejs/minerva/programs/server/packages/sanjo_jasmine.js:2051:4
  at /var/nodejs/minerva/programs/server/packages/sanjo_jasmine.js:2060:3
  at /var/nodejs/minerva/programs/server/boot.js:205:10
  at Array.forEach (native)
  at Function._.each._.forEach (/var/nodejs/minerva/programs/server/node_modules/underscore/underscore.js:79:11)
  at /var/nodejs/minerva/programs/server/boot.js:116:5
```

I'm using sanjo:jasmine 0.12.3. Doing the same thing without the --debug options works fine.
Maybe this issue is related with this? https://github.com/meteor-velocity/velocity/issues/146

**Comment by Sanjo** [comment]
Still a problem.

**Comment by Sanjo** [comment]
Found the source of the issue: It's the NODE_ENV check in velocity:core.

https://github.com/meteor-velocity/velocity/blob/master/src/core.js#L20

__Open question__: Should Velocity be available in this situation?

**Comment by think01** [comment]
I think yes, it should. Since I'm building a debug bundle, I'm supposed to do some testing so probably I still want all the test facility to be in place. At least it's true for my use case.
