### ISSUE TITLE
Integration tests fail sometimes even though the spy expected/actuals match

### ISSUE THREAD

**Issue by shrop** [Sanjo/meteor-jasmine#218]
Integration tests fail sometimes even though the spy expected/actuals match. It is odd as this happens sometimes and then other times, it works.

Just wanted to report to see if there are any suggestions for me to check on my end.

Also, this happens locally and on our Jenkins CI server.

```
[34mW20150530-18:07:52.498(0)? (STDERR) [39m[35mjasmine-server-integration: 1 tests failed[39m
[34mW20150530-18:07:52.498(0)? (STDERR) [39m[35mlogActivity server method saves an activity document to the posts collection[39m
[34mW20150530-18:07:52.499(0)? (STDERR) [39m[35mExpected spy insert to have been called with [ { type: 'post', sourceId: '45B7E9XDWgm9ZKXdv', userId: 'piFFMxysCsNCwjw9S', timestamp: Date(Sat May 30 2015 18:07:25 GMT+0000 (UTC)) } ] but actual calls were [ { type: 'post', sourceId: '45B7E9XDWgm9ZKXdv', userId: 'piFFMxysCsNCwjw9S', timestamp: Date(Sat May 30 2015 18:07:25 GMT+0000 (UTC)) } ].[39m
[34mW20150530-18:07:52.499(0)? (STDERR) [39m[35mError: Expected spy insert to have been called with [ { type: 'post', sourceId: '45B7E9XDWgm9ZKXdv', userId: 'piFFMxysCsNCwjw9S', timestamp: Date(Sat May 30 2015 18:07:25 GMT+0000 (UTC)) } ] but actual calls were [ { type: 'post', sourceId: '45B7E9XDWgm9ZKXdv', userId: 'piFFMxysCsNCwjw9S', timestamp: Date(Sat May 30 2015 18:07:25 GMT+0000 (UTC)) } ].[39m
[34mW20150530-18:07:52.499(0)? (STDERR) [39m[35m  at stack (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1441:17)[39m
[34mW20150530-18:07:52.499(0)? (STDERR) [39m[35m  at buildExpectationResult (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1411:14)[39m
[34mW20150530-18:07:52.500(0)? (STDERR) [39m[35m  at Spec.Env.expectationResultFactory (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:533:18)[39m
[34mW20150530-18:07:52.500(0)? (STDERR) [39m[35m  at Spec.addExpectationResult (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:293:34)[39m
[34mW20150530-18:07:52.500(0)? (STDERR) [39m[35m  at Expectation.addExpectationResult (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:477:21)[39m
[34mW20150530-18:07:52.500(0)? (STDERR) [39m[35m  at Expectation.toHaveBeenCalledWith (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1365:12)[39m
[34mW20150530-18:07:52.500(0)? (STDERR) [39m[35m  at Object.<anonymous> (app/tests/jasmine/server/integration/logActivity/logActivity.js:14:29)[39m
[34mW20150530-18:07:52.501(0)? (STDERR) [39m[35m  at attemptSync (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1759:24)[39m
[34mW20150530-18:07:52.501(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1747:9)[39m
[34mW20150530-18:07:52.501(0)? (STDERR) [39m[35m  at QueueRunner.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1733:10)[39m
[34mW20150530-18:07:52.501(0)? (STDERR) [39m[35m  at Spec.Env.queueRunnerFactory (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:569:35)[39m
[34mW20150530-18:07:52.502(0)? (STDERR) [39m[35m  at Spec.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:318:10)[39m
[34mW20150530-18:07:52.502(0)? (STDERR) [39m[35m  at Object.fn (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2072:43)[39m
[34mW20150530-18:07:52.502(0)? (STDERR) [39m[35m  at attemptAsync (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1789:24)[39m
[34mW20150530-18:07:52.502(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1745:16)[39m
[34mW20150530-18:07:52.502(0)? (STDERR) [39m[35m  at QueueRunner.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1733:10)[39m
[34mW20150530-18:07:52.502(0)? (STDERR) [39m[35m  at Suite.Env.queueRunnerFactory [as queueRunner] (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:569:35)[39m
[34mW20150530-18:07:52.503(0)? (STDERR) [39m[35m  at Suite.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2055:10)[39m
[34mW20150530-18:07:52.503(0)? (STDERR) [39m[35m  at Object.fn (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2072:43)[39m
[34mW20150530-18:07:52.503(0)? (STDERR) [39m[35m  at attemptAsync (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1789:24)[39m
[34mW20150530-18:07:52.503(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1745:16)[39m
[34mW20150530-18:07:52.504(0)? (STDERR) [39m[35m  at /var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1771:16[39m
[34mW20150530-18:07:52.504(0)? (STDERR) [39m[35m  at /var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1716:9[39m
[34mW20150530-18:07:52.504(0)? (STDERR) [39m[35m  at complete (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2067:9)[39m
[34mW20150530-18:07:52.504(0)? (STDERR) [39m[35m  at QueueRunner.clearStack (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:555:9)[39m
[34mW20150530-18:07:52.504(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1754:12)[39m
[34mW20150530-18:07:52.505(0)? (STDERR) [39m[35m  at /var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1771:16[39m
[34mW20150530-18:07:52.505(0)? (STDERR) [39m[35m  at /var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1716:9[39m
[34mW20150530-18:07:52.506(0)? (STDERR) [39m[35m  at complete (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:330:9)[39m
[34mW20150530-18:07:52.506(0)? (STDERR) [39m[35m  at QueueRunner.clearStack (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:555:9)[39m
[34mW20150530-18:07:52.506(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1754:12)[39m
[34mW20150530-18:07:52.506(0)? (STDERR) [39m[35m  at QueueRunner.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1733:10)[39m
[34mW20150530-18:07:52.506(0)? (STDERR) [39m[35m  at Spec.Env.queueRunnerFactory (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:569:35)[39m
[34mW20150530-18:07:52.506(0)? (STDERR) [39m[35m  at Spec.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:318:10)[39m
[34mW20150530-18:07:52.507(0)? (STDERR) [39m[35m  at Object.fn (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2072:43)[39m
[34mW20150530-18:07:52.507(0)? (STDERR) [39m[35m  at attemptAsync (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1789:24)[39m
[34mW20150530-18:07:52.507(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1745:16)[39m
[34mW20150530-18:07:52.507(0)? (STDERR) [39m[35m  at /var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1771:16[39m
[34mW20150530-18:07:52.507(0)? (STDERR) [39m[35m  at /var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1716:9[39m
[34mW20150530-18:07:52.507(0)? (STDERR) [39m[35m  at complete (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:330:9)[39m
[34mW20150530-18:07:52.507(0)? (STDERR) [39m[35m  at QueueRunner.clearStack (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:555:9)[39m
[34mW20150530-18:07:52.507(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1754:12)[39m
[34mW20150530-18:07:52.507(0)? (STDERR) [39m[35m  at QueueRunner.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1733:10)[39m
[34mW20150530-18:07:52.508(0)? (STDERR) [39m[35m  at Spec.Env.queueRunnerFactory (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:569:35)[39m
[34mW20150530-18:07:52.508(0)? (STDERR) [39m[35m  at Spec.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:318:10)[39m
[34mW20150530-18:07:52.620(0)? (STDERR) [39m[35m  at Object.fn (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2072:43)[39m
[34mW20150530-18:07:52.620(0)? (STDERR) [39m[35m  at attemptAsync (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1789:24)[39m
[34mW20150530-18:07:52.620(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1745:16)[39m
[34mW20150530-18:07:52.620(0)? (STDERR) [39m[35m  at QueueRunner.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1733:10)[39m
[34mW20150530-18:07:52.620(0)? (STDERR) [39m[35m  at Suite.Env.queueRunnerFactory [as queueRunner] (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:569:35)[39m
[34mW20150530-18:07:52.621(0)? (STDERR) [39m[35m  at Suite.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2055:10)[39m
[34mW20150530-18:07:52.621(0)? (STDERR) [39m[35m  at Object.fn (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2072:43)[39m
[34mW20150530-18:07:52.621(0)? (STDERR) [39m[35m  at attemptAsync (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1789:24)[39m
[34mW20150530-18:07:52.621(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1745:16)[39m
[34mW20150530-18:07:52.621(0)? (STDERR) [39m[35m  at QueueRunner.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1733:10)[39m
[34mW20150530-18:07:52.621(0)? (STDERR) [39m[35m  at Suite.Env.queueRunnerFactory [as queueRunner] (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:569:35)[39m
[34mW20150530-18:07:52.622(0)? (STDERR) [39m[35m  at Suite.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2055:10)[39m
[34mW20150530-18:07:52.622(0)? (STDERR) [39m[35m  at Object.allFns.push.fn (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:599:82)[39m
[34mW20150530-18:07:52.622(0)? (STDERR) [39m[35m  at attemptAsync (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1789:24)[39m
[34mW20150530-18:07:52.622(0)? (STDERR) [39m[35m  at QueueRunner.run (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1745:16)[39m
[34mW20150530-18:07:52.622(0)? (STDERR) [39m[35m  at QueueRunner.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1733:10)[39m
[34mW20150530-18:07:52.622(0)? (STDERR) [39m[35m  at Env.queueRunnerFactory (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:569:35)[39m
[34mW20150530-18:07:52.622(0)? (STDERR) [39m[35m  at Env.execute (/var/lib/jenkins/.meteor/packages/sanjo_jasmine/.0.13.7.nwz71c++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:606:7)[39m
[34mW20150530-18:07:52.622(0)? (STDERR) [39m[35m  at [object Object]._.extend.runTests (/tmp/meteor-test-run1g9q1ih/.meteor/local/build/programs/server/packages/sanjo_jasmine.js:623:14)[39m
[34mW20150530-18:07:52.622(0)? (STDERR) [39m[35m  at Object.<anonymous> (/tmp/meteor-test-run1g9q1ih/.meteor/local/build/programs/server/packages/sanjo_jasmine.js:582:14)[39m
[34mW20150530-18:07:52.623(0)? (STDERR) [39m[35m  at Object.<anonymous> (/tmp/meteor-test-run1g9q1ih/.meteor/local/build/programs/server/packages/underscore.js:784:19)[39m
[34mW20150530-18:07:52.623(0)? (STDERR) [39m[35m  at [object Object].observeChangesCallbacks.added (/tmp/meteor-test-run1g9q1ih/.meteor/local/build/programs/server/packages/minimongo.js:3901:28)[39m
[34mW20150530-18:07:52.623(0)? (STDERR) [39m[35m  at Object.self.applyChange.added (/tmp/meteor-test-run1g9q1ih/.meteor/local/build/programs/server/packages/minimongo.js:3801:44)[39m
[34mW20150530-18:07:52.623(0)? (STDERR) [39m[35m  at Object.task (/tmp/meteor-test-run1g9q1ih/.meteor/local/build/programs/server/packages/minimongo.js:397:13)[39m
[34mW20150530-18:07:52.623(0)? (STDERR) [39m[35m  at [object Object]._.extend._run (/tmp/meteor-test-run1g9q1ih/.meteor/local/build/programs/server/packages/meteor.js:769:18)[39m
[34mW20150530-18:07:52.623(0)? (STDERR) [39m[35m  at /tmp/meteor-test-run1g9q1ih/.meteor/local/build/programs/server/packages/meteor.js:747:14[39m
[34mW20150530-18:07:52.623(0)? (STDERR) [39m[35m[39m
```

**Comment by Sanjo** [comment]
Most likely the timestamp is the cause. Can you try to output the two dates as milliseconds (date.getTime()). Maybe there is a difference sometimes.

**Comment by shrop** [comment]
will do! sorry to take so long to get back. still seeing this one occasionally. now on jenkins too.

**Comment by shrop** [comment]
@Sanjo 

I am not sure how to do what you asked in this context. Figure you seeing my test may help you know what I am doing here. I may be approaching the spy wrong. https://gist.github.com/shrop/536979155d253009db80

**Comment by Sanjo** [comment]
Change the `timestamp: new Date()` to `timestamp: jasmine.any(Date)`.

**Comment by Sanjo** [comment]
If you care about the date value, use this technique: http://jasmine.github.io/2.1/introduction.html#section-Mocking_the_Date

**Comment by shrop** [comment]
thank you, @Sanjo!
