### ISSUE TITLE
Jasmine can't find an exported global (a class) using Babel based ES6 code

### ISSUE THREAD

**Issue by sebastianconcept** [Sanjo/meteor-jasmine#230]
Here is a repo showing the issue:
https://github.com/sebastianconcept/jasmineAndES6

And a stack trace:
```
ReferenceError: Model is not defined
    at Object.<anonymous> (/Users/sebastian/git/jasmineAndES6/tests/jasmine/server/unit/ModelSpec.es6.js:6:17)
    at attemptSync (/Users/sebastian/.meteor/packages/sanjo_jasmine/.0.14.0.3u5xia++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1759:24)
    at QueueRunner.run (/Users/sebastian/.meteor/packages/sanjo_jasmine/.0.14.0.3u5xia++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1747:9)
    at QueueRunner.execute (/Users/sebastian/.meteor/packages/sanjo_jasmine/.0.14.0.3u5xia++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1733:10)
    at Spec.Env.queueRunnerFactory (/Users/sebastian/.meteor/packages/sanjo_jasmine/.0.14.0.3u5xia++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:569:35)
    at Spec.execute (/Users/sebastian/.meteor/packages/sanjo_jasmine/.0.14.0.3u5xia++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:318:10)
    at Object.fn (/Users/sebastian/.meteor/packages/sanjo_jasmine/.0.14.0.3u5xia++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2072:43)
    at attemptAsync (/Users/sebastian/.meteor/packages/sanjo_jasmine/.0.14.0.3u5xia++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1789:24)
    at QueueRunner.run (/Users/sebastian/.meteor/packages/sanjo_jasmine/.0.14.0.3u5xia++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1745:16)
    at QueueRunner.execute (/Users/sebastian/.meteor/packages/sanjo_jasmine/.0.14.0.3u5xia++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1733:10)```

**Comment by Sanjo** [comment]
Hi, the server unit mode doesn't support ES6. Can you please use the server integration  mode to write your unit tests. Thanks.

**Comment by sebastianconcept** [comment]
That makes sense.

Thank you @Sanjo !
