### ISSUE TITLE
Minimongo error.

### ISSUE THREAD

**Issue by vrecluse** [Sanjo/meteor-jasmine#63]
My code goes here (in coffeescript):
<pre><code>
describe "Chat", ->
  it "should contain 1 message after insert()", ->
    collection = new Meteor.Collection(null)
    collection.insert({username:'guest', message : 'hi'})
    expect(collection.find({}).count()).not.toBe(0 )
</code></pre>
When runs in Meteor, it complains:
<pre><code>
Error: TypeError: Cannot read property '_docs' of undefined
  at [object Object].LocalCollection.Cursor._getRawObjects (/Users/user/WebstormProjects/mud-craft/.meteor/local/build/programs/server/packages/minimongo.js:512:18)
  at [object Object].LocalCollection.Cursor.count (/Users/user/WebstormProjects/mud-craft/.meteor/local/build/programs/server/packages/minimongo.js:260:15)
  at Object.<anonymous> (/Users/user/WebstormProjects/mud-craft/tests/jasmine/server/unit/sample_server_test.coffee:6:5)
</code></pre>
But it's ok in product code.
It's a new project and I've updated meteor and packages to the latest version, did I miss something?

**Comment by Sanjo** [comment]
Should work in Client Integration mode without the Meteor stubs as intended.
